gems: [jekyll-paginate]

# Site settings
title: Opalist
email: hello@whitefusion.io
description: latest news on Opal, Ruby-to-JS toolkit
baseurl: ""
url: "http://opalist.co"

author:
  name     : 'Jared White'
  email    : hello@whitefusion.io
  url      : http://whitefusion.io
#  facebook : http://facebook.com/fernando.dev
#  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/polished-rb/opalist.co
#disqus_shortname: "fernandomoreira"
google_analytics: UA-28477462-7

paginate: 6
comments: false
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
